#!/bin/sh

if [ ".$1" = ".-3e509704-b9ba-11e7-94ed-9337b5773949" ]; then
    shift
    mc=NO
else
    # Midnight Commander
    mc=YES
fi

if [ -z "$DISPLAY" ]; then
    /usr/bin/vim -- "$@"
    return
fi

if [ $# -eq 0 ]; then
    s=""
    while [ -e "untitled$s" ]; do
        s=$(($s+1))
    done
    set -- "untitled$s"
fi

# Guardians for '-*', '*.geany', and ':*' files.
n=$#
i=0
for a in "$@"; do
    i=$(($i+1))
    if [ $i -gt $n ]; then
        break
    fi
    if [ ".$(printf %.1s "$a")" = "./" ]; then
        xa="$a"
    else
        xa="./$a"
    fi
    s=0
    while [ -e "$xa:0:$s" ]; do
        s=${s}0
    done
    set -- "$@" "$xa:0:$s"
done
for i in {1..$n}; do
    shift
done

if [ "$mc" = "NO" ]; then
    /usr/bin/geany -i -c "$HOME/.config/geany-editor" "$@"
else
    (/usr/bin/geany -c "$HOME/.config/geany-editor" "$@" > /dev/null 2>&1 &)
fi
